pipeline {
  agent none
  stages {
    stage('build') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        git 'https://github.com/fr-dev-rao/java-project.git'
        sh 'mvn --version'
        sh 'mvn compile'
        sh 'mvn test'
        sh 'mvn package'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npm install'
      }
    }
  }
}
